### PR TITLE
Added mailcatcher, Improvements in ajax calls related to follow. completes #198?

### PR DESCRIPTION
**Pull request by sonalkr132**
I merged the master and changes I proposed in #231. A lot of improvements were made since then, I thought it would better to work with them. It kinda makes PR really log, but you need to review only last 3 commits. 

* I have added [mailcatcher](http://mailcatcher.me/). I guess we would need to update [user instructions wiki](https://github.com/glittergallery/GlitterGallery/wiki/Usage-Instructions) 

* Follow button on project page was a anchor tag, so it was sending a GET request. I updated routes.rb. I know I am violation RESTful urls but we haven't been very respectful of the concept in rest of project either :stuck_out_tongue_winking_eye: We need to refactor our routes file. 

* Fixed 401 error on clicking of follow by guest user. Now page redirects to root. 

* Fixed issues raised in #198  by @rohitpaulk about UX. In my implantation, user sees new followers list if he clicks on follow or unfollow. Also fixed handling of active class of social tabs.

Does this closes #198 or do you have any other improvements in mind?

### CODE REVIEW

**Comment by rohitpaulk** [comment]
70 commits?? :open_mouth: 

Please rebase on master, and base the PR on glittergallery:master instead of glittergallery:show_followers.

**Comment by sonalkr132** [comment]
I didn't make all of them. I thought it would be better idea if I merge show-followers branch with master before I start making changes to it, so that I don't have to deal with merge conflicts with master later on. 

Was it a bad idea? IDK! 

I didn't send merge request on master branch because I wanted to work on issue on show-followers and I was unsure if after my changes we will be done with it. Like what if you guys suggested something more enhancements to "followers feature".  

Only last three commits in my PR need to be reviewed, rest are exact ones from master.

**Comment by rohitpaulk** [comment]
> I didn't send merge request on master branch because I wanted to work on issue on show-followers and I was unsure if after my changes we will be done with it. Like what if you guys suggested something more enhancements to "followers feature".

I feel that incremental changes are the best to work with. If we need enhancements, let's open them in a separate PR. :)

**Comment by sonalkr132** [comment]
Yeah, we would use a separate PR not a separate branch right. My changes were related to this branch hence I sent it here.

Should I rebase it and sent PR on master instead?

**Comment by rohitpaulk** [comment]
> Should I rebase it and sent PR on master instead?

Please do, and we'll close Sarup's PR as all of his commits would be included in yours.

**Pull request closed without merging**
