### PR TITLE
Rubocop spec

### PR DESCRIPTION
**Pull request by sonalkr132**
I do need a few suggestions. Does this look readable? Those 3 closing brackets one after look weird.
```Ruby
expect(Rugged::Repository.new(File.join(
      @project.data_path,
      'satellite',
      '.git'
    ))).to be_a(Rugged::Repository)
```

I had to change name of argument `password_confirmation` to `password_confirm`  here:
```Ruby
def sign_up_with(email, username, password, password_confirm = password)
  visit '/'
  click_link 'Sign Up?'
  # more_code
end
```
Both cases were violating line length limit. How could I have done better?

### CODE REVIEW

**Comment by Alwahsh** [comment]
LGTM :+1:

**Comment by rohitpaulk** [comment]
> Those 3 closing brackets one after look weird.

You could split the file_name out to a variable, and use that in the statement.

> I had to change name of argument password_confirmation to password_confirm here:

That's fine. 

Great work, thanks! I'm going to merge this.

**Comment by sonalkr132** [comment]
How much priority should we give to this:
screenshot from 2015-03-24 21 36 06

**Comment by rohitpaulk** [comment]
> How much priority should we give to this:

I think all those warnings are valid, and should be taken care of. This isn't very different from the cleanup we've been doing till now.

**Comment by sonalkr132** [comment]
I want to get this cleaning code thing out of our way, I am gonna work on this too. I mentioned it [here](https://github.com/glittergallery/GlitterGallery/issues/258#issuecomment-84150580),  so just double checking :yum:

**Comment by sonalkr132** [comment]
I strongly suggest that we change default line width to 100 for haml files. 
screenshot from 2015-03-25 00 59 04

Top one is not only has lesser readability but association between those two lines is also obscure.

**Comment by rohitpaulk** [comment]
> I strongly suggest that we change default line width to 100 for haml files. 

Makes sense.

**Pull request merged**
