### PR TITLE
Fix 157

### PR DESCRIPTION
**Pull request by sarupbanskota**

### CODE REVIEW

**Comment by sarupbanskota** [comment]
update: this doesn't work in production, I don't know why (yet).

**Comment by sarupbanskota** [comment]
*kicks self* I pushed the wrong branch. Seems good on my deployment: glittery-banas.rhcloud.com

**Comment by sarupbanskota** [comment]
@rohitpaulk this can be merged, travis fails but it's obvious cuz it doesn't find the omniauth buttons it's looking for: https://travis-ci.org/glittergallery/GlitterGallery/builds/48224616#L354

**Comment by rohitpaulk** [comment]
The way I see it - this functionality is just a safeguard for production environments where people forget to set the env vars. I've pushed a commit to perform the check only in production.

**Comment by rohitpaulk** [comment]
@sarupbanskota - Feel free to merge this once you're reviewed it.

**Comment by sarupbanskota** [comment]
I agree, makes sense. Merging.

**Pull request merged**
