### PR TITLE
Fixed notification toolbar

### PR DESCRIPTION
**Pull request by mecyborg**

### CODE REVIEW

**Comment by mecyborg** [comment]
Fixes #249

**Comment by mecyborg** [comment]
@EmilyDirsh Please verify. Thanks.

**Comment by sarupbanskota** [comment]
could you please pull from master and also link to a demo?

**Comment by mecyborg** [comment]
@sarupbanskota updated with master.
Should i create a new demo for this ?

**Comment by mecyborg** [comment]
@sarupbanskota Demo Link: http://ggdemo-shifton.rhcloud.com/

Please check.

**Comment by sarupbanskota** [comment]
Verified, this is ready to merge, however I have two requests: 
* Could you add a link to the Notifications page under "Settings" on this screenie?
screenshot from 2015-03-20 18 49 54
* Could you collapse all your work into one commit - after all the merges etc, 8 commits is a lot for a small change :)

Thanks!

**Comment by rohitpaulk** [comment]
> Could you collapse all your work into one commit - after all the merges etc

Also, is there a specific reason for using `merge` instead of `rebase`? If there isn't, please use `rebase` from now on :)

**Comment by mecyborg** [comment]
Discard this PR. 
New PR #271 submitted with all changes.

**Pull request closed without merging**
