### PR TITLE
Remove all assets from the repo.

### LINKED ISSUE #243: Resolving the assets issue
If I understood what's going on correctly, openshift has problems with compiling our assets on deployment.
The current solution is to compile the assets manually whenever we introduce a change to the assets and push it with the source code. This makes the repo keep getting bigger and bigger with every simple change in the assets.

If we can't resolve the openshift issue with compilation. I suggest that the user is advised to do the compilation thing by himself instead of adding them to the repo like now.

### PR DESCRIPTION
**Pull request by Alwahsh**
Remove all compiled assets from the repo and make openshift compile them on deployment.
Resolves #243

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@Alwahsh - I can't view the diff on GitHub coz too many files have been changed. Can you split 'deleting assets' and 'configuring openshift to precompile' into two separate commits?

**Comment by Alwahsh** [comment]
@rohitpaulk configuring openshift to precompile is just actually deleting one file but I'm doing what you suggested now :)

**Comment by Alwahsh** [comment]
@rohitpaulk done :)

**Comment by Alwahsh** [comment]
@rohitpaulk the repo language statistics definitely look better now, right? :)

**Comment by rohitpaulk** [comment]
Hehe yh man, they're starting to make sense now ;)

**Comment by Alwahsh** [comment]
:)

**Pull request merged**
