### PR TITLE
Basically PRs : #226, #231, #245

### PR DESCRIPTION
**Pull request by sonalkr132**
#226 #231 and #245 

Sorry, I had to merge all the changes I made, cause I had changed state of my database (as suggested by @rohitpaulk parent was renamed to parent_id). It was either that or going through every file and changing parent to parent_id, which would create merge conflicts with my other PRs. 

#226 and #231 were almost reviewed my @EmilyDirsh , Their commits are from "17cbaa" (upgrade to rails 4.1) to "1a7b84"(changed project to local variable) look [here](https://github.com/glittergallery/GlitterGallery/pull/231/commits)

You just need to review my last three commits. Refer to #245 for explanation of changes being made.

Have you seen a PR worse that this? -_-

### CODE REVIEW

**Comment by Alwahsh** [comment]
The fork network in #240 eliminates the need for changes in the forking system since it kinda replaces it... There'd be no parent column in the table at all.

**Comment by sonalkr132** [comment]
lol. Another merge conflict. Yay!

**Comment by sonalkr132** [comment]
On a serious note! You should email me, your email is not public. We got to have better coordination.

**Comment by Alwahsh** [comment]
Yeah, sorry about that :) We should've considered the general case from the beginning. This one shouldn't be that hard to merge anyways :)... I'm sending you an e-mail.

**Pull request closed without merging**
