### PR TITLE
fix broken images in production #260

### LINKED ISSUE #260: use of  OPENSHIFT_DATA_DIR
#228 leads to broken image
screenshot from 2015-03-13 09 56 22
You might say, lets use 
```Ruby
elsif Rails.env.production?
	Glitter::Application.config.repo_dir=ENV['OPENSHIFT_DATA_DIR'] +"data/"
```
But things don't get any easier, as openshift seem to have bug related to OPENSHIFT_DATA_DIR. image's path get resolved to "/var/lib/openshift/xxxxx/app-root/data/....." instead of "app-root/data/..." where files are originally stored and where OPENSHIFT_DATA_DIR originally points to. look [here] (https://developers.openshift.com/en/managing-filesystem.html#__code_data_code). If interested further [read](https://bugzilla.redhat.com/show_bug.cgi?id=962432)

I kinda hacked my way with by adding following in .openshift/action_hooks/build:
`ln -sf ../../../../app-root/data ${OPENSHIFT_REPO_DIR}/public/data`

does anyone have better idea?

### PR DESCRIPTION
**Pull request by sonalkr132**
fixes #260

### CODE REVIEW

**Comment by rohitpaulk** [comment]
https://github.com/glittergallery/GlitterGallery/issues/260#issuecomment-80923550

**Comment by sonalkr132** [comment]
actually this just fixes current situation.. where images are broken because of:
```
elsif Rails.env.production?
  Glitter::Application.config.repo_dir="ENV['OPENSHIFT_DATA_DIR']/data"
```

**Comment by rohitpaulk** [comment]
`"#{ENV['OPENSHIFT_DATA_DIR']}/data"` is what you're looking for, then.

**Comment by sonalkr132** [comment]
`"#{ENV['OPENSHIFT_DATA_DIR']}/data"` leads to same effect as `ENV['OPENSHIFT_DATA_DIR']+"/data"`

screenshot from 2015-03-13 09 56 22

Cause there seems to be a bug in openshift. read #260

**Comment by sonalkr132** [comment]
`"#{ENV['OPENSHIFT_DATA_DIR']}/data"` leads to same effect as `ENV['OPENSHIFT_DATA_DIR']+"/data"`

screenshot from 2015-03-13 09 56 22

Cause there seems to be a bug in openshift. read #260

**Comment by rohitpaulk** [comment]
> "#{ENV['OPENSHIFT_DATA_DIR']}/data" leads to same effect as ENV['OPENSHIFT_DATA_DIR']+"/data"

Yes, I know. That's why I posted a comment on #260. https://github.com/glittergallery/GlitterGallery/issues/260#issuecomment-80923550

**Pull request merged**
